### ISSUE TITLE
File cleanup

### ISSUE THREAD

**Issue by chpxu** [chpxu/vscode-firefox-quantum-themes#24]
I can tell the files are getting very very cluttered. I've been able to get by adding random and relevant scopes to certain "fitting" areas, but as stated in #23, I am thinking of making changes. Consequently, there will have to be changes in how development is made. There are a few possible paths. 

### Advantages 
- This would make it easier to see which scopes affect which language
- Allow for more specific per-language customisation without breaking anything else
### Disadvantages
- Lots of duplicate keys, which would make it pointless to maintain. It may become more bloated. 

### Advantages
- Allows a much morw viewable hierarchy of scopes
- Easier to maintain (to a good degree) 
- Covers more languages without having to delve into specifics
### Disadvantages
- The hierarchy doesn't always stay 100%. At certain times, I must be more specific, however it shouldn't be that much of a problem if I group by scope
- Harder to spot individual languages

### Advantages
- Easy colour reference
- Allows for appropiate places to place new scopes
### Disadvantages
- Not very useful in displaying which scopes are where and identifying languages 

## Path D - Combination of A and B
This would mean almost every scope would have a language extension (such as `. php`) and there'd be a clear hierarchy of scopes per language. The current idea for this Path is sorting by language, then making specific hierarchy of scopes withi n each one. 

### Advantages
- Very easy to see and maintain
- Endless limits to customisation
- Less error prone
### Disadvantages
- Much more effort, but worth it
- Will require more tinkering, especially with #23

Currently leaning towards Path D

**Comment by compilenix** [comment]
Option D surely involves the most effort, but i think it could be worth it.

**Comment by beastdestroyer** [comment]
Option D would be the most successful. Positive management of file space and it's a go!

**Comment by beastdestroyer** [comment]
Would create a `languages` folder and put syntax highlighting for each one. It may be hard however since if a highlight breaks, we'd have to check each one and ensure it is fine. However since we end it in a language extension, this shouldn't be the case and will allow for endless customisation
