### ISSUE TITLE
Interfaces should have different color in TypeScript typing

### ISSUE THREAD

**Issue by motss** [chpxu/vscode-firefox-quantum-themes#42]
**Describe the bug**
Interfaces should have different color when it is declared in a TypeScript typing file. As shown in the screenshot in the `Screenshots` section, the line `interface A {` has the exact same color for each token just like how interface name `A` is colored in the line `interface C extends A`. Type aliases should also need to have a different color in the line `type D = A | B`.

Please find attached the screenshots showing the existing colorization as well as a proposed solution for better code readability.

**Screenshots**

**Existing**
<img width="154" alt="Screen Shot 2020-01-17 at 1 57 27 PM" src="https://user-images.githubusercontent.com/10607759/72587921-a86b3380-3931-11ea-9c69-a015e750129e.png">

**Proposed**
<img width="152" alt="Screen Shot 2020-01-17 at 2 07 12 PM" src="https://user-images.githubusercontent.com/10607759/72588266-af467600-3932-11ea-9f17-ce6d861d4cd4.png">

**Environment:** 
 - Other Data:  TypeScript typing
 - Theme Version: `1.1.9`

**Additional context**

**Comment by beastdestroyer** [comment]
Apologies for the 2 month reply, 

In accordance with the Firefox DevTools console, I have applied the blue colour instead of the purple colour used in your screenshot.

It also looks to fit the scheme much better. Thank you for raising this issue, in the next update, this shall be a change.

**Comment by chpxu** [comment]
WIll add as an update in 1.2.0 see #44
