### ISSUE TITLE
Request: Better PHP support

### ISSUE THREAD

**Issue by iPurpl3x** [chpxu/vscode-firefox-quantum-themes#43]
This theme is really amazing but as much as I prefer to work with JS most of the time, I also have to write and read PHP quite often... This theme seems to not be very optimized for that programming language... 

Could someone take care of making it a bit less monotonous ?

<img width="718" alt="image" src="https://user-images.githubusercontent.com/18526076/147543741-7427de1d-036b-4ca4-9627-8bcb492d7a86.png">

**Comment by iPurpl3x** [comment]
@chpxu or @compilenix are you still maintaining this or not ?

**Comment by chpxu** [comment]
I will see what I can do though last time I remember, PHP was quite hard to work with unless it's changed in the past 3 years or with a PHP extension

**Comment by compilenix** [comment]
> @chpxu or @compilenix are you still maintaining this or not ?

I'm not a maintainer, i've only tested stuff and suggested minor changes. This is not my field of expertise.

**Comment by iPurpl3x** [comment]
@chpxu Nice, thanks ! 

In the meantime I found a similar theme that works fine with PHP : `linlong-95.firefoxtheme`

@compilenix ok understood 😉

**Comment by chpxu** [comment]
Thanks for the recommendation. so far I've changed classes/types to be yellow and SQL has changed syntax highlighting too (see 1.2.0-beta1 and see if it is to your preference). I've made other changes that I think suit the theme better also.

**Comment by iPurpl3x** [comment]
How can I install this beta version ?...

**Comment by chpxu** [comment]
Here's a somewhat quick way: first go to
`./vscode/extensions/beastdestroyer.firefox-quantum-themes` and go to the `themes` folder. 

Download the repo (`master` branch) and unzip it. Paste all the files into this folder and if it asks to overwrite/replace, press confirm.

Restart VSCode and the themes should apply. To undo your change, uninstall the extension (and just to be safe, check the same folder and delete it from `./vscode/extensions`)

If you use the Insiders build, the vscode folder is `./vscode-insiders`
